services:
  postgres:
    image: postgres:16-alpine # ставим легковесный образ бд
    container_name: accelerator-postgres
    environment: # задаем переменные среды, образ сам создаст пользователя с таким паролем и создаст бд с таким именем
      POSTGRES_USER: "${POSTGRES_USER}" 
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports: # пробрасываем порт из контейнера на локальную машину, чтобы можно было подключиться вне контейнера
      - "5432:${POSTGRES_PORT}"
    volumes: # сохраняем данные с бд из контейнера в папку на локальной машине, чтобы не стирались при перезагрузке контейнера
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # проверка, работает ли база данных каждые n секунд
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: # подключаем к созданной локальной сети, чтобы контейнеры могли общаться между собой 
      - accelerator-network

  minio:
    image: minio/minio:latest
    container_name: accelerator-minio
    command: server /data --console-address ":9001"
    environment: # образ сам создаст пользователя с таким паролем
      MINIO_ROOT_USER: "${S3_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${S3_SECRET_ACCESS_KEY}"
      MINIO_SERVER_URL: "${MINIO_SERVER_URL}" # чтобы генерировать публичные ссылки с моим вдресом, а не minio:9000
      MINIO_BROWSER_CORS: "${CLIENT_URL}" # чтобы клиент мог взаимодействовать с s3
      MINIO_API_CORS_ALLOW_ORIGIN: "${CLIENT_URL}" # ставим корсы для взаимодействия с бакетом
    expose: # 9000 - порт самого клиента minio, 9001 - веб-консоль небольшой графический интерфейс
      - "${S3_CLIENT_PORT}"
      - "${S3_CONSOLE_PORT}"
    volumes: # также прокидываем общую папку, чтобы данные не удалялись
      - minio_data:/data
    networks:
      - accelerator-network


  migrate:
    image: migrate/migrate:v4.17.0
    container_name: accelerator-migrate
    volumes:
      - ./migrations:/migrations # монтируем папку с миграциями внутрь докер контейнера
    command: ["-path", "/migrations", "-database", "${DB_DSN}", "up"] # сразу накатываем все миграции при запуске приложения
    depends_on: # ставиим зависимость, что выполнять миграции можно только если бд работает нормально
      postgres:
        condition: service_healthy
    networks:
      - accelerator-network

  app:
    build: . # берем образ из докер файла
    container_name: accelerator-go
    environment: # так как мы не кидаем туда .env, нам нужно предоставить доступ к переменным из него
      # === Config.ServerPort ===
      SERVER_PORT: "${SERVER_PORT}"

      # === Config.ClientURLs (список через запятую) ===
      CLIENT_URLS: "${CLIENT_URLS}"

      # === JWT и время жизни токенов ===
      JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"     # Config.JWTAccessSecret
      JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"   # Config.JWTRefreshSecret
      ACCESS_TIME_MINUTE: "${ACCESS_TIME_MINUTE}"   # Config.AccessTime (минуты)
      REFRESH_TIME_HOURS: "${REFRESH_TIME_HOURS}"   # Config.RefreshTime (часы)

      # === MinIO / S3 ===
      S3_ENDPOINT: "${S3_ENDPOINT}"                 # Config.MinioEndpoint
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"       # Config.MinioAccessKey
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}" # Config.MinioSecretKey
      S3_BUCKET: "${S3_BUCKET}"                     # Config.MinioBucket
      S3_USESSL: "${S3_USESSL}"                     # Config.MinioSSL (true/false)

      PRESIGNED_PUBLIC_HOST_NAME: "${PRESIGNED_PUBLIC_HOST_NAME}"


      # === База данных ===
      DB_DSN: "${DB_DSN}"                           # Config.DBDSN

      # === Лимиты и настройки приложения ===
      SIZE_LIMIT_AUDIO_MB: "${SIZE_LIMIT_AUDIO_MB}"               # Config.SizeLimitAudioMB
      GENERATE_PASSWORD_LENGTH: "${GENERATE_PASSWORD_LENGTH}"     # Config.GeneratePasswordLength
      LIMIT_UPLOAD_AUDIO_MINUTE: "${LIMIT_UPLOAD_AUDIO_MINUTE}"   # Config.LimitUploadAudioMinutes (минуты)
      MAX_UPLOAD_WORKERS: "${MAX_UPLOAD_WORKERS}"                 # Config.MaxUploadWorkers
      AI_WORKERS_HTTP_TIMEOUT_HOURS: "${AI_WORKERS_HTTP_TIMEOUT_HOURS}" # Config.AIWorkersTimeoutHour (часы)
      LIMIT_AUDIO_URL_MINUTS: "${LIMIT_AUDIO_URL_MINUTS}"         # Config.LimitAudioURLMinuts (минуты)
      LIMIT_LOAD_DURATION_SECONDS: "${LIMIT_LOAD_DURATION_SECONDS}" 

      # === Ресурсы сервера (для балансировки очередей) ===
      TOTAL_VRAM_GB: "${TOTAL_VRAM_GB}"             # Config.TotalVRAMGB
      TOTAL_RAM_GB: "${TOTAL_RAM_GB}"               # Config.TotalRAMGB

      # === URL-адреса AI-воркеров (StageConfig.EndPoint) ===
      DENOISE_WORKER_URL: "${DENOISE_WORKER_URL}"   # для этапа denoise
      DIARIZE_WORKER_URL: "${DIARIZE_WORKER_URL}"   # для этапа diarize
      TRANSCRIBE_WORKER_URL: "${TRANSCRIBE_WORKER_URL}" # для этапа transcribe
      SUMMARY_WORKER_URL: "${SUMMARY_WORKER_URL}"   # для этапа summarize
    volumes: # пробрасываем папку с логами напрямую в докер контейнер 
      - ./logs:/root/logs
    expose:
      - "${GO_SERVER_PORT}"
    depends_on:
      migrate: # ждем пока миграции успешно применятся и запустится объектное хранилище
        condition: service_completed_successfully
      minio:
        condition: service_started
    networks:
      - accelerator-network


  denoise-worker:
    build:
      context: ./ai/denoise   # путь к папке с Dockerfile и кодом
      dockerfile: Dockerfile
    container_name: accelerator-denoise-worker
    volumes: # один раз загружаем модель и сохраняем в valume, чтобы не загружать несколько раз заново
    - denoise_models:/app/models
    expose:    # в локальной сети итак все приложения видят порты друг друга, это просто как документация
    - "${DENOISE_PORT}"   # просто подсказка, реальной безопасности не добавляет
    # Важно: поддержка GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: uvicorn denoise:app --host 0.0.0.0 --port ${DENOISE_PORT} # команда запуска
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    networks:
      - accelerator-network

  diarize-worker:
    build:
      context: ./ai/diarize
      dockerfile: Dockerfile
    container_name: accelerator-diarize-worker
    environment:
      HF_TOKEN: ${DIARIZE_HF_TOKEN} # токен Hugging Face из .env
      HF_HOME: "/app/models/huggingface" # кеш моделей
    volumes:
      - diarize_models:/app/models # том для сохранения моделей
    expose:
      - "${DIARIZE_PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: uvicorn diarize:app --host 0.0.0.0 --port ${DIARIZE_PORT} # команда запуска
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    networks:
      - accelerator-network


  asr-worker:
    build:
      context: ./ai/transcribe
      dockerfile: Dockerfile
    container_name: accelerator-asr-worker
    environment:
      HF_HOME: "/app/models/huggingface"
      MODELSCOPE_CACHE: "/app/models/modelscope"
    volumes:
      - asr_models:/app/models
    expose:
      - "${TRANSCRIBE_PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: uvicorn transcribe:app --host 0.0.0.0 --port ${TRANSCRIBE_PORT} # команда запуска
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    networks:
      - accelerator-network


  summarize-worker:
    build:
      context: ./ai/summarize
      dockerfile: Dockerfile
    container_name: accelerator-summarize-worker
    environment:
      LOCAL_MODEL_PATH: "/app/models/qwen-model.gguf" # путь внутри контейнера к локальной модели
    volumes:
      - ./models:/app/models # папка с моделями на хосте
    expose:
      - "${SUMMARIZE_PORT}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    command: uvicorn summarize:app --host 0.0.0.0 --port ${SUMMARIZE_PORT} # команда запуска
    restart: unless-stopped
    depends_on:
      app:
        condition: service_started
    networks:
      - accelerator-network

  
  frontend:
    build:
      context: ../frontend # Поднимаемся на уровень выше и заходим в соседнюю папку frontend
      dockerfile: Dockerfile
    container_name: accelerator-frontend
    expose:
      - "${FRONTEND_PORT}" # Открываем порт 8080 на сервере Ubuntu и направляем его на 80 порт Nginx
    depends_on:
      app:
        condition: service_started
    networks:
      - accelerator-network
    restart: unless-stopped

  # запускает nginnx с первичными временными сертификатами и насттройками
  nginx: 
    image: nginx:alpine
    container_name: accelerator-nginx
    user: root
    environment:
      - MAX_BODY_SIZE=${SIZE_LIMIT_AUDIO_MB}   # подставится в nginx, например, "4096M"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro # пробрасываем конфиг nnginx
      - certbot-etc:/etc/letsencrypt:rw # пробрасываем именованные тома с сертификатами в контейнер
      - certbot-www:/var/www/certbot:ro
      - ./nginx-entrypoint.sh:/docker-entrypoint.d/00-cert-init.sh:rw   # монтируем наш скрипт, чтобы он запукался при запуске с базовыми настройками и сертификатами
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - accelerator-network
    restart: unless-stopped
    healthcheck:   # чтобы certbot знал, что nginx жив
      test: ["CMD", "pgrep", "nginx"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис удалит временные сертификаты и создаст новые
  certbot-init:
    image: certbot/certbot:latest
    container_name: accelerator-certbot-init
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    environment: # передаем переменные окружения для передачи в команду
      - EMAIL_CERTBOT=${EMAIL_CERTBOT}
      - CLIENT_CERTBOT_1=${CLIENT_CERTBOT_1}
      - CLIENT_CERTBOT_2=${CLIENT_CERTBOT_2}
      - MINIO_CERTBOT=${MINIO_CERTBOT}
    entrypoint: /bin/sh -c "sleep 15; rm -rf /etc/letsencrypt/live /etc/letsencrypt/archive /etc/letsencrypt/renewal; certbot certonly --webroot --webroot-path=/var/www/certbot --email $EMAIL_CERTBOT --agree-tos --no-eff-email --force-renewal -d $CLIENT_CERTBOT_1 -d $CLIENT_CERTBOT_2 -d $MINIO_CERTBOT;"
    depends_on:
      nginx: # запустится, когда будет живой nginx
        condition: service_healthy
    networks:
      - accelerator-network

  # Автоматическое обновление сертификатов (запускается периодически)
  # certbot-renew обновит сертификаты в томе, но nginx продолжит держать в памяти старые, поэтому перезагружаем его через docker Api
  certbot-renew:
    build:
      context: .
      dockerfile: certbot-renew.Dockerfile
    container_name: accelerator-certbot-renew
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock   # даём доступ к Docker API
    networks:
      - accelerator-network

  # сервис перезапустит контейнер после получения новых сертификатов, заставит nginx перечитать конфигурацию и сертификаты без разрыва соединений
  reload-nginx:
    image: docker:cli
    container_name: accelerator-reload-nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "sleep 5 && docker kill -s HUP accelerator-nginx"
    depends_on: # запустится, когда будет выполнен контейнер выпуска сертификатов
      certbot-init:
        condition: service_completed_successfully
    networks:
      - accelerator-network


volumes: # используем именованные тома, а не привязка к конкретной папке
  postgres_data:
  minio_data:
  denoise_models:
  diarize_models:
  asr_models:

  certbot-etc:
  certbot-www:

networks:
  accelerator-network:
    driver: bridge