server {
    listen 8080;
    server_name букволов-ии.рф www.букволов-ии.рф localhost;
    
    
    # Разрешаем загружать огромные файлы (до 1000 МБ)
    client_max_body_size 1000M;


    # Отдаем статику собранного фронтенда
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Важно для SPA-роутера (React Router, Vue Router), чтобы не было 404 при обновлении страницы
        try_files $uri $uri/ /index.html;
    }

    # Все запросы, начинающиеся с /api, перенаправляем в контейнер бэкенда
    location /api/ {
        # 'app' — это имя сервиса бэкенда в твоем docker-compose.yml
        # ВАЖНО: Укажи здесь внутренний порт контейнера (значение твоей переменной ${GO_SERVER_PORT}, обычно 8000 или 8080)
        # Слэш на конце обязателен — он отрезает '/api' из пути, так же как мы делали в vite.config.ts
        proxy_pass http://app:8000/; 
        proxy_request_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 9000;
    server_name букволов-ии.рф www.букволов-ии.рф localhost;

    # Без ограничений на размер файлов (MinIO обрабатывает сам)
    client_max_body_size 0;

    location / {
        proxy_pass http://minio:9000;

        # ★ Фиксируем заголовок Host, под который подписаны Presigned URL (внутреннее имя сервиса)
        proxy_set_header Host minio:9000;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Пробрасываем авторизационные заголовки (важно для MinIO)
        proxy_pass_request_headers on;
    }
}